[[sound_preset]]
name = "default"
key_config = [
  { event = "press", keys = "Return", files = [
    { path = "ding.mp3", volume = 1.0 },
  ] },
  { event = "press", keys = ".*", variation = { volume = [0.1, 0.1], tempo = [0.05, 0.05] }, files = [
    { path = "keydown.mp3", volume = 1.0 },
  ] },
  { event = "release", keys = ".*", variation = { volume = [0.1, 0.1], tempo = [0.05, 0.05] }, files = [
    { path = "keyup.mp3", volume = 1.0 },
  ] },
]


[[sound_preset]]
name = "basic"
key_config = [
  { event = "press", keys = "Return", files = [
    { path = "newline.mp3" },
  ] },
  { event = "press", keys = ".*", files = [
    { path = "keystroke.mp3" },
  ] },
]


[[sound_preset]]
name = "musicbox"
key_config = [
  { event = "press", keys = ".*", files = [
    { path = "mbox1.mp3" },
    { path = "mbox2.mp3" },
    { path = "mbox3.mp3" },
    { path = "mbox4.mp3" },
    { path = "mbox5.mp3" },
    { path = "mbox6.mp3" },
    { path = "mbox7.mp3" },
    { path = "mbox8.mp3" },
  ], strategy = "random" },
]

[[sound_preset]]
name = "mechanical"
key_config = [

  { event = "press", keys = ".*", files = [
    { path = "1.wav" },
    { path = "2.wav" },
    { path = "3.wav" },
    { path = "4.wav" },
    { path = "5.wav" },
  ], strategy = "random" },
]

[[sound_preset]]
name = "drum"
key_config = [
  { event = "press", key = "backspace", files = [
    { path = "backspace.wav" }
  ] }
  ,
  { event = "press", key = "enter", files = [
    { path = "enter.wav" }
  ] }
  ,
  { event = "press", key = "space", files = [
    { path = "space.wav" }
  ] }
  ,
  { event = "press", keys = ".*", files = [
    { path = "1.wav" },
    { path = "2.wav" },
    { path = "3.wav" },
    { path = "4.wav" },
  ]  ,strategy ="random"}
]

[[sound_preset]]
name = "typewriter"
key_config = [
  { event = "press", key = "backspace", files = [
    { path = "backspace.wav" }
  ] }
  ,
  { event = "press", key = "return", files = [
    { path = "return.wav" }
  ] }
  ,
  { event = "press", key = "space", files = [
    { path = "space.wav" }
  ] }
  ,
  { event = "press", keys = ".*", files = [
    { path = "1.wav" },
    { path = "2.wav" },
    { path = "3.wav" },
    { path = "4.wav" },
    { path = "5.wav" },
  ]  ,strategy ="random"}

]


[[sound_preset]]
name = "ducktilo"
key_config = [
  { event = "press", keys = "Return", files = [
    { path = "quack2.mp3" },
  ] },
  { event = "press", keys = ".*", files = [
    { path = "quack1.mp3", volume = 10.0 },
  ] },
]

[[sound_preset]]
name = "drumkit"
key_config = [
  { event = "press", keys = ".*", files = [
    { path = "kick.mp3" },
    { path = "hat.mp3" },
    { path = "snare.mp3" },
    { path = "kick.mp3" },
    { path = "hat.mp3" },
    { path = "kick.mp3" },
    { path = "snare.mp3" },
    { path = "hat.mp3" },
  ], strategy = "sequential" },
]

# Sparks
# For a high voltage high current typing experience
[[sound_preset]]
name = "sparks"
key_config = [
  { event = "press", keys = "Backspace", files = [
    { path = "derase.mp3" },
  ], strategy = "random" },
  { event = "press", keys = ".*", files = [
    { path = "dspark1.mp3" },
    { path = "dspark2.mp3" },
    { path = "dspark3.mp3" },
    { path = "dspark4.mp3" },
    { path = "dspark5.mp3" },
    { path = "dspark6.mp3" },
  ], strategy = "random" },
]

