name: "🐛 快速反馈 / Bug report"
title: "[BUG] "
description: "反馈你遇到的问题 / Report the issue you are experiencing"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 在提交问题之前，请确认以下事项：
        3. 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索

  - type: input
    id: version
    attributes:
      label: "当前使用的软件版本 / Current Software Version"
      description: |
        请填写你当前使用的软件版本号， ⚠️ 请优先确保你使用的是最新版本，以避免已修复的问题。
      placeholder: "例如：1.2.3"
    validations:
      required: true


  - type: textarea
    id: description
    attributes:
      label: "问题描述 / Describe the bug"
      description: "详细清晰地描述你遇到的问题，并配合截图 / Describe the problem you encountered in detail and clearly, and provide screenshots"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "复现步骤 / To Reproduce"
      description: "请提供复现问题的步骤 / Steps to reproduce the behavior"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
    validations:
      required: true

