version: '7.7.7'
name: master-pipeline
displayName: HyperScoopMasterPipeline
stages:
  - stage:
    name: release
    displayName: 发布
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: '自动发布 来自CI/CD'
        # 上游上传制品任务的产出
        dependArtifact:  target\release\hp.exe
        # 发布制品版本号
        version: '1.0.0.0'
        # 是否开启版本号自增，默认开启
        autoIncrement: true
triggers:
  push:
    branches:
      include:
        - master
