[package]
name = "command_util_lib"
version = "0.1.0"
edition.workspace = true
publish = { workspace = true }
authors = { workspace = true }
description = "hyperscoop 的后端, 用于处理命令行参数 ,加载一些系统配置等"
license = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
rust-version = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
serde = { workspace = true }
log = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
serde_json = "1.0.132"
regex = "1.11.1"
crossterm = { workspace = true }
chrono = "0.4.38"
reqwest = "0.12.9"
zip = "2.2.0"
encoding_rs = "0.8.35"
encoding = "0.2.33"
repair_json = "0.1.0"


[lib]
name = "command_util_lib"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"

