name: Hp  Release Pipeline
on:
  push:
    branches: ["main"]
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.arch }}-pc-windows-msvc
      - run: cargo build  --target ${{ matrix.arch }}-pc-windows-msvc --release
      - name: Upload build artifact for ${{ matrix.arch }}  # 传递构建产物给 publish job
        uses: actions/upload-artifact@v4
        with:
          name: hp-${{ matrix.arch }}
          path: target/${{ matrix.arch }}-pc-windows-msvc/release/hp.exe


  publish:
    needs:   [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Git (for fetch tags)
        run: git fetch --tags

      - name: Get version tag from Python script
        id: version
        shell: pwsh
        run: |
          $new_tag = python script/get_latest_version.py
          $new_tag = $new_tag.Trim()  # 去掉换行和空格
          echo "new_tag=$new_tag" >> $env:GITHUB_OUTPUT

      - name: Download x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: hp-x86_64
          path: x64

      - name: Download x86 artifact
        uses: actions/download-artifact@v4
        with:
          name: hp-i686
          path: x86

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: hp-aarch64
          path: arm64

      - name: Rename Artifacts
        shell: pwsh
        run: |
         $tag = ${{ steps.version.outputs.new_tag }}
         Copy-Item "x64\hp.exe"     "$env:GITHUB_WORKSPACE\hp-x64-$tag.exe"
         Copy-Item "x86\hp.exe"     "$env:GITHUB_WORKSPACE\hp-x86-$tag.exe"
         Copy-Item "arm64\hp.exe"   "$env:GITHUB_WORKSPACE\hp-arm64-$tag.exe"

      - name: Create Release And Upload Build Artifacts
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}

        with:
          name: "Hp  '${{ steps.version.outputs.new_tag }}'  is published"
          tag_name:   ${{ steps.version.outputs.new_tag }}
          body:  "More new features are now supported."
          files: |
             hp-x64-${{ steps.version.outputs.new_tag }}.exe
             hp-x86-${{ steps.version.outputs.new_tag }}.exe
             hp-arm64-${{ steps.version.outputs.new_tag }}.exe
