name: Hp  Release Pipeline
on:
  push:
    branches: ["main"]
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.arch }}-pc-windows-msvc
      - run: cargo build  --target ${{ matrix.arch }}-pc-windows-msvc --release

  publish:
    needs:   [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.release.name || github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ github.event.release.body || 'Automated release' }}
          files: |
            release/*.exe
            release/*.exe.sha256
